# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse lazily follows any focus (window or workspace)
on-focus-changed = ['move-mouse window-lazy-center'] 

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
alt-enter = '''exec-and-forget osascript -e '
tell application "Kitty"
    do script
    activate
end tell'
'''

ctrl-alt-shift-h = 'focus left'
alt-ctrl-shift-j = 'focus down'
alt-ctrl-shift-k = 'focus up'
alt-ctrl-shift-l = 'focus right'

alt-ctrl-cmd-shift-h = 'move left'
alt-ctrl-cmd-shift-j = 'move down'
alt-ctrl-cmd-shift-k = 'move up'
alt-ctrl-cmd-shift-l = 'move right'


ctrl-alt-shift-down = 'resize smart -50'
ctrl-alt-shift-left = 'resize smart -100'
ctrl-alt-shift-up = 'resize smart +50'
ctrl-alt-shift-right = 'resize smart +100'


alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

ctrl-alt-shift-f = 'fullscreen'

ctrl-alt-shift-r = 'reload-config'
# alt-s = 'layout v_accordion' # 'layout stacking' in i3
# alt-w = 'layout h_accordion' # 'layout tabbed' in i3
# alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

ctrl-alt-shift-1 = 'workspace 1'
ctrl-alt-shift-2 = 'workspace 2'
ctrl-alt-shift-3 = 'workspace 3'
ctrl-alt-shift-4 = 'workspace 4'
ctrl-alt-shift-5 = 'workspace 5'
ctrl-alt-shift-6 = 'workspace 6'
ctrl-alt-shift-7 = 'workspace 7'
ctrl-alt-shift-8 = 'workspace 8'
ctrl-alt-shift-9 = 'workspace 9'
ctrl-alt-shift-0 = 'workspace 10'

alt-ctrl-cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-ctrl-cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-ctrl-cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-ctrl-cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-ctrl-cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-ctrl-cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-ctrl-cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-ctrl-cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-ctrl-cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-ctrl-cmd-shift-0 = ['move-node-to-workspace 10', 'workspace 10']


# App specific Workspaces
ctrl-alt-shift-b = 'workspace B'
ctrl-alt-shift-c = 'workspace C'
ctrl-alt-shift-d = 'workspace D'
ctrl-alt-shift-e = 'workspace E'
ctrl-alt-shift-i = 'workspace I'
ctrl-alt-shift-m = 'workspace M'
ctrl-alt-shift-n = 'workspace N'
ctrl-alt-shift-o = 'workspace O'
ctrl-alt-shift-p = 'workspace P'
ctrl-alt-shift-t = 'workspace T'

alt-ctrl-cmd-shift-b = ['move-node-to-workspace B', 'workspace B']
alt-ctrl-cmd-shift-c = ['move-node-to-workspace C', 'workspace C']
alt-ctrl-cmd-shift-d = ['move-node-to-workspace D', 'workspace D']
alt-ctrl-cmd-shift-e = ['move-node-to-workspace E', 'workspace E']
alt-ctrl-cmd-shift-i = ['move-node-to-workspace I', 'workspace I']
alt-ctrl-cmd-shift-m = ['move-node-to-workspace M', 'workspace M']
alt-ctrl-cmd-shift-n = ['move-node-to-workspace N', 'workspace N']
alt-ctrl-cmd-shift-o = ['move-node-to-workspace O', 'workspace O']
alt-ctrl-cmd-shift-p = ['move-node-to-workspace P', 'workspace P']
alt-ctrl-cmd-shift-t = ['move-node-to-workspace T', 'workspace T']

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace T' # mnemonics T - Terminal

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace T' # mnemonics T - Terminal

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace B' # mnemonics B - Browser

[[on-window-detected]]
if.app-id = 'com.adobe.illustrator'
run = 'move-node-to-workspace I' # mnemonics I - Illustrator

[[on-window-detected]]
if.app-id = 'com.adobe.Photoshop'
run = 'move-node-to-workspace P' # mnemonics P - Photoshop

[[on-window-detected]]
if.app-id = 'com.adobe.InDesign'
run = 'move-node-to-workspace D' # mnemonics D - Design

[[on-window-detected]]
if.app-id = 'com.atlassian.trello'
run = 'move-node-to-workspace O' # mnemonics O - Orgo

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace C' # mnemonics C - Chat

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace E' # mnemonics E - E-Mail

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace M' # mnemonics M - Music






[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        20
outer.right =      20

